name: Docker Image CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main", "testing" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajsokolik
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        run: |
          DATE_TAG=$(date +%F)
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "DATE_IMAGE_TAG=$DATE_TAG" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "testing" ]; then
            # Add timestamp to make testing tags unique
            TIMESTAMP=$(date +%H%M%S)
            echo "IMAGE_TAG=testing" >> $GITHUB_ENV
            echo "DATE_IMAGE_TAG=testing-$DATE_TAG-$TIMESTAMP" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          pull: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.DATE_IMAGE_TAG }}
            ghcr.io/ajsokolik/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ghcr.io/ajsokolik/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.DATE_IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }},mode=max,optional=true
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }},mode=max

      - name: Capture image digest
        if: always()
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.DATE_IMAGE_TAG }} 2>/dev/null || echo "")
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Show push status
        run: |
          if [ "${{ steps.build.outputs.digest }}" != "" ]; then
            echo "✅ Image built and pushed. Digest: ${{ steps.build.outputs.digest }}"
          else
            echo "ℹ️ No changes detected. Image push was skipped."
          fi

      - name: Create GitHub release
        if: steps.build.outputs.digest != ''
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.DATE_IMAGE_TAG }}
          release_name: "Build ${{ env.DATE_IMAGE_TAG }}"
          body: |
            Docker image pushed with digest: ${{ steps.build.outputs.digest }}
          draft: false
          prerelease: ${{ github.ref_name == 'testing' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
