name: Docker Image CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main", "testing" ]
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajsokolik
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set image tags based on branch
      - name: Set image tags
        run: |
          DATE_TAG=$(date +%F)
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "DATE_IMAGE_TAG=$DATE_TAG" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "testing" ]; then
            echo "IMAGE_TAG=testing" >> $GITHUB_ENV
            echo "DATE_IMAGE_TAG=testing-$DATE_TAG" >> $GITHUB_ENV
          fi

      # Build and push Docker image with optional cache
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          pull: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.DATE_IMAGE_TAG }}
            ghcr.io/ajsokolik/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ghcr.io/ajsokolik/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.DATE_IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }},mode=max,optional=true
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }},mode=max
          outputs: type=image,attr=digest

      # Friendly log message
      - name: Show push status
        run: |
          if [ "${{ steps.build.outputs.digest }}" != "" ]; then
            echo "✅ Image built and pushed. Digest: ${{ steps.build.outputs.digest }}"
          else
            echo "ℹ️ No changes detected. Image push was skipped."
          fi

      # Create a GitHub release for this build (date-based tag)
      - name: Create GitHub release
        if: steps.build.outputs.digest != ''
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.DATE_IMAGE_TAG }}
          release_name: "Build ${{ env.DATE_IMAGE_TAG }}"
          body: |
            Docker image pushed with digest: ${{ steps.build.outputs.digest }}
          draft: false
          prerelease: ${{ github.ref_name == 'testing' }}
          token: ${{ secrets.GH_PAT }}  # <- pass PAT here
